- zos_concepts/encoding/convert_encoding/convert_encoding.yaml
> Corrected bug where from_encoding and to_encoding were inverted

- README.md
This PR adds a link to the z/OS User Management With Ansible blog under the blogs section of the README
> add user management blog to README

- zos_concepts/data_sets/copy_edit_submit/copy_edit_submit.yml
- zos_concepts/data_sets/data_set_basics/data_set_basics.yaml
- zos_concepts/data_transfer/copy_fetch_data_set/copy_fetch_data_set.yaml
- zos_concepts/data_transfer/terse_fetch_data_set/terse_fetch_data_set.yml
- zos_concepts/jobs/submit_query_retrieve/submit_query_retrieve.yml
This PR addresses [NAZARE-2811](https://jsw.ibm.com/browse/NAZARE-2811), where temporary data sets used on the sample playbooks should have unique names to prevent name collisions.
> Generate random temp data set name

- README.md
This commit updates the repositories README to better reflect that the playbooks span the entire Z platform and not only z/OS. This prepares us for upcoming playbooks for Z.
Signed-off-by: ddimatos <dimatos@gmail.com>
> Added minor updates to the README to reflect the broader Z offering

- zos_administration/host_setup/filter_plugins/command_paths.py
- zos_administration/host_setup/host_setup.yaml
- zos_administration/host_setup/tasks/choose_zoau.yml
- zos_administration/host_setup/templates/host_vars.j2
- zos_administration/host_setup/templates/test-vars.j2
This PR adds logic to the host-setup playbook to address the special installation requirements of ZOAU 1.1.0, additional changes should (hopefully) not be required for newer versions.
> add zoau 1.1.0 support to host-setup playbook

- docs/share/configuration_guide.md
Signed-off-by: ddimatos <dimatos@gmail.com>
Updated documentation for use with unsupported Bash shell configuration. Even though unsupported at the current time, little has been done to allow Ansible to work with Bash on Z. I would like to preserve the work done thus far for when there is time to extend our support to Bash, there is a starting point and for those who don't have access to another shell be given the same starting point.
> Update configuration guide with unsupported Bash configuration

- cics/README.md
- cics/cmci/deploy_program/README.md
- cics/cmci/deploy_program/host_vars/zos_host.yml
- cics/cmci/override_failure/README.md
- cics/cmci/reporting/README.md
Added a top-level README for the CICS collection samples, to list out the available samples and give them a proposed ordering.
Also a couple of tweaks for terminology.
> Add README for CICS collection samples

- zos_concepts/zos_operator/zos_operator_basics/zos_operator_basics.yaml
Signed-off-by: ddimatos <dimatos@gmail.com>
This changes and corrects the WTO response used. Technically there is no such reply `cancel` , the correct response would be `end` and then a clean up routine to remove the temporary data set. This fix only addresses the change to use `end`. A separate change will be done to clean up the temporary data set as its not currently logic in this flow. 
Playbook output:
```
ddimatos:[ ~/git/github/playbooks ]ansible-playbook -i inventory zos_operator_basics.yaml
PLAY [zvm] **************************************************************************************************************************************************************
TASK [Detecting system name] ************************************************************************************************ …
```
> Bugfix wto reply, change from cancel to end

- zos_administration/host_setup/filter_plugins/command_paths.py
- zos_administration/host_setup/filter_plugins/command_strings.py
Signed-off-by: ddimatos <dimatos@gmail.com>
Both filters below did not have an encoding defined in the Python source which on my system threw a "Non-ASCII character '\xc2' in file error". 
This should correct both plugins:
- /host_setup/filter_plugins/command_paths.py
- zos_administration/host_setup/filter_plugins/command_strings.py
> Update filters with added python source code encoding for xc2 error

- zos_subsystems/cics/README.md
This adds a reference to the root README, useful for those who have been pointed directly at the CICS README.
> Refer to the main repo README in the CICS README

- z_infra_provisioning/cloud_infra_center/ocp_upi/inventory.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-dns/templates/etc/named.conf.j2
Fixed: https://github.com/IBM/z_ansible_collections_samples/issues/73
> [cloud_infra_center] Set named allowed query range as cluster subnet range

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
> [cloud_infra_center] Ignore the server group warning when deploying OCP control plane.

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-network.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/inventory.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network-existing/tasks/main.yaml
1. Update inventory.yaml with existing network
test scenario:
1.1) Failed when the user does not specify use_existing_network_name
1.2) Failed when the user does not specify use_existing_network_subnet
1.3) Update DNS name server and allocation pool 
2. Update Readme, and add HAProxy record when user wants to use own DNS and HAProxy.
> Fix ocp 6534 - Use existing network to deploy OCP UPI

- z_infra_provisioning/cloud_infra_center/ocp_upi/inventory.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-dns/templates/etc/named.conf.j2
After this change, user can specify another nameserver as a forwarder when configuring bastion's DNS. So that some requests which can not be resolved by bastion's DNS and be forwarded to the specified nameserver.
> [cloud_infra_center] Add dns forwarder option

- z_infra_provisioning/cloud_infra_center/ocp_upi/down-network.yaml
Fix issue 6564 - Remove destroy network step when executing down-network.yaml
> [cloud_infra_center]  Remove destroy network step when executing down-network.yaml

- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/modify-bastion.py
fix: #88 
After this change, when using the cluster name contains "-" strings, like "openshift-bj-cluster1", the bastion template yaml will not be messed.
> [cloud_infra_center] Fix bug: #88

- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
Add disk type support for "scsi" when creating bootstrap, master and worker.
Test on 172.26.4.143 test stand:
```
[root@m5404-integ-contro ocp_upi]# ansible-playbook -i inventory.yaml configure-bootstrap.yaml
PLAY [Create the bootstrap server] **********************************************************************************************************************************************************************
TASK [Gathering Facts] **********************************************************************************************************************************************************************************
ok: [localhost]
TASK [configure-bootstrap : Export Infra ID] ****************************************************************************************************************************** …
```
> Fix-ocp-6751: Add scsi disk type when creating nodes

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network-existing/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network/tasks/main.yaml
If user only input one of items of allocation_pool_start or allocation_pool_end, it will skip creating network.
After this change, it will be failed and throw out error msg, if user do so, like this:
```
[root@m5404-integ-contro ocp_upi]# ansible-playbook -i inventory.yaml configure-network.yaml 
PLAY [Configure existing network] ***************************************************************************************************************
TASK [Gathering Facts] **************************************************************************************************************************
ok: [localhost]
TASK [configure-network-existing : Export Infra ID] *********************************************************************************************
changed: [localhost]
TASK …
```
> [cloud_infra_center] Add check for allocation pool

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
Fix a syntax error in configure-control-plane.yaml, which was brought in https://github.com/IBM/z_ansible_collections_samples/pull/91.
> [cloud_infra_center] Fix a syntax typo in configure-control-plane.yaml

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-dns/tasks/main.yml
1) Deploy OCP successfully with this PR on KVM test stand 100.8 ( allocated_ip = true) 
```
I have tested all changes successfully in ansible 2.8.18.
[root@bastion2 ocp_upi]# ansible --version
ansible 2.8.18
config file = /etc/ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.8 (default, Mar 18 2021, 08:58:30) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
[root@bastion2 ocp_upi]# oc get nodes
NAME                       STATUS   ROLES    AGE    VERSION
host-172-26-105-63         Ready    worker   3m7s   v1.20.0+c8905da
host-172-26-105-68         Ready    worker   3m9s   v1.20.0+c8905da …
```
> Add named owner and group on DNS definition

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-pre-check/tasks/main.yaml
1) Deploy OCP successfully with this PR on KVM test stand 100.8 ( allocated_ip = true) 
```
I have tested all changes successfully in ansible 2.8.18.
[root@bastion2 ocp_upi]# ansible --version
ansible 2.8.18
config file = /etc/ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.8 (default, Mar 18 2021, 08:58:30) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
[root@bastion2 ocp_upi]# oc get nodes
NAME                       STATUS   ROLES    AGE    VERSION
host-172-26-105-63         Ready    worker   3m7s   v1.20.0+c8905da
host-172-26-105-68         Ready    worker   3m9s   v1.20.0+c8905da …
```
> Update neutron command to openstack in per-check

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-haproxy/templates/etc/haproxy/haproxy.cfg.j2
Fix customized volume size when creating bootstrap, control and compute nodes with SCSI disk_type.
1) add volume_size parameter
2) convet the flavor from value to number.
Test this pr on zvm test stand：
```
TASK [Show bootstrapping log] **************************************************************************************************************************************************************************
ok: [localhost] => {
"bootstrap_log.stdout_lines": [
"time=\"2022-03-21T03:31:41-04:00\" level=info msg=\"Waiting up to 30m0s (until 4:01AM) for bootstrapping to complete...\"",
"time=\"2022-03-21T03:37:31-04:00\" level=debug msg=\"Bootstrap status: complete\"",
"time=\"2022-03-21T03:37:31-04:00\" level=info msg=\"It is now safe to remove the bootstrap resources\"", …
```
> [cloud_infra_center]convert node flavor from value to number

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/common.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-install-config.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-install-ignition.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-install-manifests.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-computes.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-controls.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-images-files.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/inventory.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bastion-properties/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-install-config/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-install-ignition/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-install-manifests/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-and-image/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-client/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-pre-check/tasks/main.yaml
This PR contains below changes:
1) add `volume_type_id` when creating virtual machine with boot volume
2) change all tasks name
Verified three situations on zvm test stand:
1) disk_type=scsi and volume_type_id=XXXXX
1.1) add new compute node
2) disk_type=scsi
2.1) add new compute node
3) disk_type=dasd
> [cloud_infra_center] add storage template when deploying nodes

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-and-image/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-client/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-pre-check/tasks/main.yaml
This PR contains some changes.
1) Remove the root user and group when downloading IMAGE and BINARY
2) Change the hard code s390x architecture
3) Remove to get subnet name when modify network
4) Doc update
I've tested the non-user `demo` to deploy UPI, here is some key comments.
- Login your ansible linux server
- useradd demo
- passwd demo
- usermod -G icic-filter demo
- sudo visudo , and add user's permission `demo  ALL=(ALL) NOPASSWD:ALL`
- following guide to download code and run playbook
- run `01-preparation.yaml` as `demo` user
- run `bastion.yaml` as `root` user because this playbook needs to configure DNS and HAPROXY in your root system
-  run `02-create-cluster-control.yaml`
```
time="2022-06-21T03:38:11-04:00" level=debug msg="Bootstrap status: complete" …
```
> [cloud_infra_center] remove root user limit

- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/modify-bastion.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network/tasks/main.yaml
Fix five issues:
1.
``` 
ansible-playbook -i inventory.yaml add-new-compute-node.yaml -e worker_number=2 -e update_bastion=true -e ip=172.26.104.126,172.26.104.116
In create server port section, there will add index into IP , add 1 index but remove 2 index, which cause the final IP become 172.26.104.12,172.26.104.11
```
2.
```
ansible-playbook -i inventory.yaml add-new-compute-node.yaml -e worker_number=1 -e update_bastion=true -e ip=172.26.104.19
```
3.
```
ansible-playbook -i inventory.yaml add-new-compute-node.yaml -e worker_number=1 -e update_bastion=true -e ip=172.26.104.176
```
4. When user assign the IP which has been used, ICIC will give error. we need to give check when modify dns and haproxy , if the ip is here, give error to inform user to use the other IPs.
5. When user does …
> [cloud_infra_center]fix fixed ip issue when add multiple workers

- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-images.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos-local/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos/tasks/main.yaml
1) add metadata `gz_sha256` when uploading rhcos image
2) rename rhcos image name from `rhcos` to `icic_rhcos_<disk_type>`
3) fix adding compute node without update_bastion parameter
Tested on kvm, zvm dasd and zvm scsi environment, all passed.
```
zvm-dasd:
[root@bastion ocp_upi]# ./oc get nodes
NAME                     STATUS   ROLES    AGE    VERSION
lynn-r4d9q-master-0      Ready    master   110m   v1.24.0+b62823b
lynn-r4d9q-master-1      Ready    master   98m    v1.24.0+b62823b
lynn-r4d9q-master-2      Ready    master   98m    v1.24.0+b62823b
lynn-r4d9q-worker-3468   Ready    worker   10m    v1.24.0+b62823b
lynn-r4d9q-worker-5456   Ready    worker   11m    v1.24.0+b62823b
lynn-r4d9q-worker-7463   Ready    worker   26m    v1.24.0+b62823b
[root@bastion ocp_upi]# openstack image list …
```
> [cloud_infra_center] update rhcos image and add gz_sha256 to verify image

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/inventory.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-client/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos/tasks/main.yaml
1. add latest tag for openshift_minor_version
2. compare the specified minor_version, if not exist, query the latest version under `openshift_version`
3. update README doc
> [cloud_infra_center] add latest tag for minor version

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-haproxy/tasks/main.yml
Fix to restart haproxy service.
Test scenario:
1. deploy OCP on kvm,  destory it and redeploy again.
2. deploy OCP on zvm-dasd,  destory it and redeploy again.
Verify the haproxy server should be restarted after running `bastion.yaml`, if not restart successfully, the master can not resolve the `api-int` domain.
> [cloud_infra_center] Update restart haproxy service

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap-zvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes-zvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane-zvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network/tasks/main.yaml
Retest with latest code on zvm test stand.
```
TASK [Show bootstrapping log] *******************************************************************************************************
ok: [localhost] => {
"bootstrap_log.stdout_lines": [
"time=\"2023-01-05T03:58:36-05:00\" level=info msg=\"Waiting up to 30m0s (until 4:28AM) for bootstrapping to complete...\"",
"time=\"2023-01-05T04:09:53-05:00\" level=debug msg=\"Bootstrap status: complete\"",
"time=\"2023-01-05T04:09:53-05:00\" level=info msg=\"It is now safe to remove the bootstrap resources\"",
"time=\"2023-01-05T04:09:53-05:00\" level=debug msg=\"Time elapsed per stage:\"",
"time=\"2023-01-05T04:09:53-05:00\" level=debug msg=\"Bootstrap Complete: 11m18s\"",
"time=\"2023-01-05T04:09:53-05:00\" level=info msg=\"Time elapsed: 11m18s\""
]
} …
```
> [cloud_infra_center] add custom_dns for zvm platform

- .gitattributes
Add a .gitattributes file with line for linguist to detect YAML so that it is shown in the 'Languages' bar on the repository's main page.
Signed-off-by: Jacob Emery <jacob.emery@ibm.com>
> Add .gitattributes to detect YAML

- zos_concepts/data_sets/data_set_basics/data_set_basics.yml
- zos_concepts/jobs/submit_query_retrieve/submit_query_retrieve.yml
generalizes the playbook more by removing direct references to the 'dimato' volume. 
removes and cleans up some of the initial fact settings - system_name is collected and set but never used. the pds data set name wasn't printed out but the sequential data set name was.
> z trial playbook edits to data set basics and submit query retrieve

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-install-config/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network/tasks/main.yaml
1. Change the network type from SDN to OVN when cluster version was after 4.12.
2. Fix the os_port can not use specified subnet when auto_allocated_ip=true.
Test scenario:
1.  Deploy OCP 4.12 version, check the `openshift-ovn-kubernetes` should use the OVNKubernetes.
2. Deploy OCP 4.11 version, check the `openshift-network` should use the OpenshiftSDN.
3. Create os_port and auto_allocated_ip=true with multiple subnets
4. Create os_port and auto_allocated_ip=false with multiple subnets
> [cloud_infra_center] Change networkType from SDN to OVN after 4.12

- README.md
Current link is a 404 as its missing the markdown file extension, this resolves that bug.
Closes #190
> Fix broken contribution guidelines link in README.md

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-install-manifests/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-security-groups/tasks/main.yaml
When install OCP with only 3 master nodes, ingress operator will be run on master nodes, which require TCP 80/443 SG rules.
> Add http/https SG rules to master SG when three nodes install

- zos_concepts/volume_management/volume_initialization/init_dasd_vol_and_run_sample_jcl/ansible.cfg
- zos_concepts/zfsadm/zfs_grow_aggr/ansible.cfg
- zos_concepts/zos_ping/ansible.cfg
Select samples that leverage the role `requirements-check` did not have the `role_path` variable set appropriately in their respective `ansible.cfg` files, thus some users experienced a role not found error.
> Roles path fixes

- zos_concepts/data_sets/data_set_basics/data_set_basics.yml
The tasks that created data sets or files before being copied to were causing the copy tasks to fail, as the destination already existed.
It suggested adding 'force: true', but that caused other problems.
These changes make it so that the playbook doesn't have these errors, and makes it fully idempotent for re-running smoothly.
Also changes some task names to be more descriptive.
Thank you to Ivan Alejandro Moreno Soto for the help on troubleshooting this in the #ansible-z-collections-guild Slack channel.
> fix: make data_set_basics playbook idempotent

- zos_concepts/volume_management/volume_initialization/init_dasd_vol_and_run_sample_jcl/init_dasd_vol_and_run_sample_jcl.yml
HELLO.JCL was changed to HELLO.jcl in the sample playbook. This was preventing the file from being copied  over successfully.
> typo in volume init playbook

- zos_concepts/certificate_management/delete_cert.yml
Change to more consistent conditional to check for whether or not the cert exsists already in delete_cert.
> fix delete cert conditional

- z_infra_provisioning/cloud_infra_center/ocp_upi/common.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/inventory.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-install-ignition/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/generate-bootstrap-ignitionshim.py
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/generate-master-ignition.sh
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/generate-worker-ignition.sh
In [documentation](https://github.com/IBM/z_ansible_collections_samples/blob/main/z_infra_provisioning/cloud_infra_center/ocp_upi/docs/add-dns-haproxy.md) we list example for DNS entries but are using the playbook generated hostnames. In customer environment they have a common OCP naming convention across x and p. They would like to add z to the environment but prefer to keep same naming convention as listed above:
```
ocp4zkboot (bootstrap)
ocp4zkm01 (master-1)
ocp4zkm02 (master-2)
ocp4zkm03 (master-3)
ocp4zkw01 (worker-1)
ocp4zkw02 (worker-2)
ocp4zkw03 (worker-3)
```
> Create node with sepcific name.

- z_infra_provisioning/cloud_infra_center/ocp_upi/Disconnected_Installation.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-haproxy/tasks/main.yml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos-local/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/mirror-registry/01-mirror-registry.sh
Fixes implemented:
1. Removed the automatic restart of the mirror registry.
2. Supported locally stored RHCOS client and images.
3. Updated the mirror registry script to support different architectures.
> add disconnected installation for ocp

- z_infra_provisioning/cloud_infra_center/ocp_upi/cluster-template.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/docs/add-dns-haproxy.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/docs/multi-cluster-bastion.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/modify-bastion.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-dns/templates/var/named/cluster_domain_name.zone.j2
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-dns/templates/var/named/cluster_domain_name.zone.j3
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/modify-bastion.py
Test okay.
```
TASK [Show openshift web-console and kubeadmin-password] *******************************************************************
ok: [localhost] => {
"webconsole.stdout_lines": [
"time=\"2024-08-15T00:54:32-05:00\" level=info msg=\"Install complete!\"",
"time=\"2024-08-15T00:54:32-05:00\" level=info msg=\"To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/tmp/ocp_upi/auth/kubeconfig'\"",
"time=\"2024-08-15T00:54:32-05:00\" level=info msg=\"Access the OpenShift web-console here: https://console-openshift-console.apps.kvm.ocp.com\"",
"time=\"2024-08-15T00:54:32-05:00\" level=info msg=\"Login to the console with user: \\\"kubeadmin\\\", and password: \\\"FFZpE-saxGz-iGhYI-cUbBZ\\\"\"",
"time=\"2024-08-15T00:54:32-05:00\" level=debug msg=\"Time …
```
> [cloud_infra_center]remove etcd info in bastion and doc

- zos_concepts/zfsadm/zfs_grow_aggr/grow_zfs_aggregate.yml
I found an instance where the module arg was not lower-cased.
> zfsadm playbook - lower-case module arg

- zos_subsystems/cics/cmci/module_defaults/README.md
- zos_subsystems/cics/cmci/override_failure/README.md
- zos_subsystems/cics/cmci/reporting/README.md
- zos_subsystems/cics/cmci/resource_lifecycle_and_csd/README.md
- zos_subsystems/cics/cmci/restart_bundles/README.md
- zos_subsystems/cics/cmci/set_ca/README.md
Fixes #210.
Change links to CICS documentation to point to the evergreen `latest` set of documentation.
Fix some 404s that occur when doing so.
> Make CICS doc links point to latest
