IBM/z_ansible_collections_samples

- dump-pack-ftp-unpack-restore/roles/get-estimated-size-of-data-sets/filter_plugins/total_size.py
Easy to review PR, forgot to update a docstring.
> Fix invalid description

- collections/requirements.yml
- user-management/host_vars/zhost.yml
- user-management/roles/add-zos-user/defaults/main.yml
- user-management/roles/add-zos-user/tasks/main.yml
- user-management/roles/remove-zos-user/defaults/main.yml
adds requirements file for collection support when using Ansible Tower. In addition, some default parameters were added and one tweak was made for AWX support of user add/remove
> Add requirements file for tower

- docs/share/configuration_guide.md
Updated the configuration guide with more anchors and reorganized for easier reading. Anchors are so i can cross link from collection doc.
> Update configuation guide with new layout and ordering

- README.md
- zos_administration/host_setup/README.md
- zos_administration/host_setup/host_setup.yaml
- zos_concepts/data_sets/copy_edit_submit/README.md
- zos_concepts/data_sets/copy_edit_submit/copy_edit_submit.yml
- zos_concepts/data_sets/data_set_basics/README.md
- zos_concepts/data_sets/data_set_basics/data_set_basics.yaml
- zos_concepts/data_transfer/copy_fetch_data_set/README.md
- zos_concepts/data_transfer/copy_fetch_data_set/copy_fetch_data_set.yaml
- zos_concepts/data_transfer/copy_sort_fetch/README.md
- zos_concepts/data_transfer/copy_sort_fetch/copy-sort-fetch.yml
- zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/README.md
- zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/dump-pack-ftp.yml
- zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/transfer-data-sets.yml
- zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/unpack-restore.yml
- zos_concepts/data_transfer/terse_fetch_data_set/README.md
- zos_concepts/data_transfer/terse_fetch_data_set/terse_fetch_data_set.yml
- zos_concepts/encoding/convert_encoding/README.md
- zos_concepts/encoding/convert_encoding/convert_encoding.yaml
- zos_concepts/jobs/submit_query_retrieve/README.md
- zos_concepts/jobs/submit_query_retrieve/submit_query_retrieve.yml
- zos_concepts/user_management/add_remove_user/README.md
- zos_concepts/user_management/add_remove_user/add-user.yml
- zos_concepts/user_management/add_remove_user/remove-user.yml
- zos_concepts/user_management/add_remove_user/send-rejection-email.yml
- zos_concepts/zos_operator/zos_operator_basics/README.md
- zos_concepts/zos_operator/zos_operator_basics/zos_operator_basics.yaml
Updated the contribution statement and added the dependency collection to each readme as requested.
> Updates to contribution statement and docs

- zos_concepts/data_transfer/copy_fetch_data_set/copy_fetch_data_set.yaml
> Changed a typo in the comments

- zos_concepts/data_sets/copy_edit_submit/README.md
- zos_concepts/data_sets/data_set_basics/README.md
- zos_concepts/data_transfer/copy_fetch_data_set/README.md
- zos_concepts/data_transfer/copy_sort_fetch/README.md
- zos_concepts/data_transfer/copy_sort_fetch/copy-sort-fetch.yml
- zos_concepts/data_transfer/copy_sort_fetch/host_vars/zos_host.yml
- zos_concepts/data_transfer/copy_sort_fetch/roles/copy-local-data/tasks/main.yml
- zos_concepts/data_transfer/terse_fetch_data_set/README.md
- zos_concepts/encoding/convert_encoding/README.md
- zos_concepts/jobs/submit_query_retrieve/README.md
- zos_concepts/zos_operator/zos_operator_basics/README.md
This PR fixes a few doc issues as well as updates the copy-sort-fetch playbook to reflect the new updates made to zos_copy module.
> Correct readme and update copy-sort-fetch playbook

- ims/ims_provisioning/README.md
- ims/ims_provisioning/roles/ims_apf/README.md
- ims/ims_provisioning/roles/ims_catalog/README.md
- ims/ims_provisioning/roles/ims_common/README.md
- ims/ims_provisioning/roles/ims_common_queue/README.md
- ims/ims_provisioning/roles/ims_dataset/README.md
- ims/ims_provisioning/roles/ims_dbrc/README.md
- ims/ims_provisioning/roles/ims_exit/README.md
- ims/ims_provisioning/roles/ims_gen/README.md
- ims/ims_provisioning/roles/ims_iefjobs/README.md
- ims/ims_provisioning/roles/ims_initialize/README.md
- ims/ims_provisioning/roles/ims_online_change/README.md
- ims/ims_provisioning/roles/ims_operations_manager/README.md
- ims/ims_provisioning/roles/ims_proclib/README.md
- ims/ims_provisioning/roles/ims_racf/README.md
- ims/ims_provisioning/roles/ims_region/README.md
- ims/ims_provisioning/roles/ims_resource_manager/README.md
- ims/ims_provisioning/roles/ims_structured_call_interface/README.md
- ims/ims_provisioning/roles/ims_sysdef/README.md
- ims/ims_provisioning/roles/install-bzip2/README.md
- ims/ims_provisioning/roles/send-templates/README.md
- ims/ims_provisioning/roles/submit-rexx/README.md
> IDReview of IMS provisioning

- .gitattributes
- README.md
- media/copy_sort_and_fetch_data_sets_on_z_OS_using_ansible.mp4
- media/managing-zos-user-with-ansible-presentation-demo.mp4
- media/synchronize_APF_authorized_libraries_from_a_gitHub_configuration.mov
Update playbook repository with playbacks done on the playbooks that are in this repository. 
Add a media folder and upload 3 playbacks.
> Upload media to playbook repository

- README.md
Also add blank lines after headings to adhere to linting recommendations.
> Add Resource lifecycle and CSD example

- zos_subsystems/zcee/api_deployment/roles/zcee_generate_sar/README.md
Correcting a typo in the `zcee_generate_sar` role README.
> README update

- zos_subsystems/cics/cmci/resource_lifecycle_and_csd/README.md
@stewartfrancis Can you please review & merge.
> Correct README.md title

- README.md
- zos_concepts/rest_apis/README.md
- zos_concepts/rest_apis/ansible.cfg
- zos_concepts/rest_apis/files/sample_definition_file.xml
- zos_concepts/rest_apis/group_vars/all.yml
- zos_concepts/rest_apis/host_vars/zos_host.yml
- zos_concepts/rest_apis/inventories/zos_host
- zos_concepts/rest_apis/uri-sample.yml
URI sample ready to be added to samples repository.
> z/OSMF URI Sample

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
Fix: https://github.com/IBM/z_ansible_collections_samples/issues/67
> [cloud_infra_center] Fix broken link in README.md

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/requirements.txt
Fixed: https://github.com/IBM/z_ansible_collections_samples/issues/77
> [cloud_infra_center] Add packages version in README.md

- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
Fix the wrong network items' name in add-new-compute-node.yaml
> [cloud_infra_center] Fix the network items in add-new-compute-node.yaml

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
1) Deploy OCP successfully with this PR on KVM test stand 100.8 ( allocated_ip = true) 
```
I have tested all changes successfully in ansible 2.8.18.
[root@bastion2 ocp_upi]# ansible --version
ansible 2.8.18
config file = /etc/ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.8 (default, Mar 18 2021, 08:58:30) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
[root@bastion2 ocp_upi]# oc get nodes
NAME                       STATUS   ROLES    AGE    VERSION
host-172-26-105-63         Ready    worker   3m7s   v1.20.0+c8905da
host-172-26-105-68         Ready    worker   3m9s   v1.20.0+c8905da …
```
> Update Readme with repo and registery

- z_infra_provisioning/cloud_infra_center/ocp_upi/02-create-cluster-control.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/03-create-cluster-compute.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/approve.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-computes.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-images-files.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-install-ignition/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network-existing/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/generate-new-worker-ignition.sh
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/generate-worker-ignition.sh
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/wait-nodes-csrs.py
1) Customize worker name as 0,1…, instead of  random worker-xxxx 
2) Update approve CSR method
3) Remove hidden json file in 04-destroy.yaml
4)  Separate DNS and LB configuration  ( bastion.ymal and dns.yaml)
> Update worker ignition and csr approve

- z_infra_provisioning/cloud_infra_center/ocp_upi/02-create-cluster-control.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-bootstrap.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-controls.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/inventory.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap/tasks/main.yaml
1. Add individual destory bootstray boolstrap playbook.
2. Add bootstrap flavor
> [cloud_infra_center] add destroy boostrap playbook and flavor

- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos/tasks/main.yaml
1. Fix the regex match for adding compute nodes
2. Add to check if kvm is iscsi disk
> [cloud_infra_center]fix regex match for adding compute nodes name

- zos_subsystems/db2/db2_discover_applications/README.md
- zos_subsystems/db2/db2_discover_applications/roles/db2_get_list_apps/README.md
- zos_subsystems/db2/db2_discover_applications/roles/db2_get_list_apps/defaults/main.yml
- zos_subsystems/db2/db2_discover_applications/roles/db2_login/README.md
- zos_subsystems/db2/db2_discover_applications/roles/db2_login/defaults/main.yml
- zos_subsystems/db2/db2_discover_applications/vars/db2_discover_applications.yml
- zos_subsystems/db2/db2_discover_subsystems/README.md
- zos_subsystems/db2/db2_discover_subsystems/roles/db2_login/README.md
- zos_subsystems/db2/db2_discover_subsystems/roles/db2_login/defaults/main.yml
- zos_subsystems/db2/db2_discover_subsystems/roles/db2_post_graphql_discovery/README.md
- zos_subsystems/db2/db2_discover_subsystems/roles/db2_post_graphql_discovery/defaults/main.yml
- zos_subsystems/db2/db2_discover_subsystems/roles/db2_put_infra_discovery/README.md
- zos_subsystems/db2/db2_discover_subsystems/roles/db2_put_infra_discovery/defaults/main.yml
- zos_subsystems/db2/db2_discover_subsystems/vars/db2_discover_subsystems.yml
- zos_subsystems/db2/db2_schema_provisioning/README.md
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_delete_app_instance/README.md
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_delete_app_instance/defaults/main.yml
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_get_app_id/README.md
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_get_app_id/defaults/main.yml
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_get_status_instance/README.md
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_get_status_instance/defaults/main.yml
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_get_subsystem_id/README.md
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_get_subsystem_id/defaults/main.yml
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_get_team_id/README.md
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_get_team_id/defaults/main.yml
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_login/README.md
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_login/defaults/main.yml
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_post_create_instance/README.md
- zos_subsystems/db2/db2_schema_provisioning/roles/db2_post_create_instance/defaults/main.yml
- zos_subsystems/db2/db2_schema_provisioning/vars/db2_schema.yml
> renamed variables

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/checkout-to-version.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/version
Signed-off-by: bjhuangr <bjhuangr@cn.ibm.com>
> Tag version 0.1.0.0

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/docs/add-dns-haproxy.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/docs/multi-cluster-bastion.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/modify-dns.yaml
Update small changes:
1) Add icic 1.1.5 and ocp 4.9 support in readme
2) Add trouble shooting
3) Add flavor disk size and http_proxy offical ocp url link
4) Fix the modify-dns section and bastion configuration
> [cloud_infra_center] modify bastion-dns and doc

- zos_management/zosmf_security_configuration_assistant/files/sca_sample_security_requirements_file.json
Update field name of sample json, as the alias of the fields name may become invalid in future.
> Update field name of sample json

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
> [cloud_infra_center] fix openstacksdk issue

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
Signed-off-by: chengz <chengz@cn.ibm.com>
> [cloud_infra_center] fix openstack package issue

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/approve_worker.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/modify-bastion.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/modify-dns.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/modify-haproxy.yaml
1.  Add multiple workers
2.  Auto to update bastion
```
ansible-playbook -i inventory.yaml add-new-compute-node.yaml -e worker_number=3 -e update_bastion=true
ansible-playbook -i inventory.yaml add-new-compute-node.yaml -e ip=x.x.x.x,x.x.x.x -e worker_number=2 -e update_bastion=true
```
> [cloud_infra_center] create multiple nodes with random worker id

- z_infra_provisioning/cloud_infra_center/ocp_upi/approve.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
Signed-off-by: zxmhome <zxmhome@zxmhomedeMacBook-Pro.local>
> [cloud_infra_center]Remove create_master failed handle.

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
Signed-off-by: zxmhome <zxmhome@zxmhomedeMacBook-Pro.local>
> [cloud_infra_center]Fix ValueError caused by os_server server_group_id dict.

- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/approve.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/approve_worker.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-pre-check/tasks/main.yaml
Signed-off-by: XiaoMei Zheng <xmzheng@cn.ibm.com>
> [cloud_infra_center]Fix ICIC 116 volume api version 3.60 issue.

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
Signed-off-by: Zheng Xiao Mei <xmzheng@cn.ibm.com>
> Fix README version error

- z_infra_provisioning/cloud_infra_center/ocp_upi/02-create-cluster-control.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/04-destroy.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/add-new-compute-node.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/common.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-bootstrap-kvm.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-bootstrap-zvm.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-compute-nodes-kvm.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-compute-nodes-zvm.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-control-plane-kvm.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/configure-control-plane-zvm.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-bootstrap.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-files.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/destroy-volumes.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap-kvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap-zvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-bootstrap/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes-kvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes-zvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-compute-nodes/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane-kvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane-zvm/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-control-plane/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos-local/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos/tasks/main.yaml
Signed-off-by: chengz <chengz@cn.ibm.com>
> [cloud_infra_center] fix gpfs bfv issue

- z_infra_provisioning/cloud_infra_center/ocp_upi/version
Signed-off-by: Zheng Xiao Mei <xmzheng@cn.ibm.com>
> [cloud_infra_center]Tag version 0.1.0.1

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-network/tasks/main.yaml
1. Remove the dns force update for subnet
2. Add ICIC 1.1.6 support
3. Update ReadME for subnet DNS
> [cloud_infra_center] Remove the force update dns and update Doc

- .ansible-lint
- .github/actions/install-requirements/action.yml
- .github/workflows/ansible-lint.yml
- .gitignore
- collections/requirements.yml
- z_systems_administration/zhmc/playbooks/module_attach_crypto_byname.yml
This PR is a subset of #187. It purely turns on the linting, though disables all rules that are currently being infringed.
This should be easier to review, and can be followed up by multiple PRs that progressively enable rules while fixing their issues.
> Add Ansible Lint workflow (small)

- z_infra_provisioning/cloud_infra_center/ocp_upi/README.md
Update ReadMe for multiple load balancer.
> [cloud_infra_center] add multiple haproxy warning

- zos_concepts/user_management/add_remove_user/roles/add-zos-user/tasks/main.yml
- zos_concepts/user_management/add_remove_user/roles/add-zos-user/templates/define-alias.j2
- zos_concepts/user_management/add_remove_user/roles/remove-zos-user/tasks/main.yml
fixing a few small bugs with the user management sample.
> Add user bugs

- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/generate-bootstrap-ignitionshim.py
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/generate-master-ignition.sh
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/generate-worker-ignition.sh
> Fix no name_prefix issue.

- zos_subsystems/cics/README.md
- zos_subsystems/cics/provisioning/full_provision_smss.yml
> Edits to README

- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-client/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/roles/configure-installer-rhcos/tasks/main.yaml
- z_infra_provisioning/cloud_infra_center/ocp_upi/tools/mirror-registry/01-mirror-registry.sh
Test:
```
[root@integrate-ocp ~]# curl -s https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/latest-4.15/release.txt | grep 'Name:' | awk -F: '{print $2}' | xargs
[root@integrate-ocp ~]# wget -q -O - https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/latest-4.15/release.txt | grep 'Name:' | awk -F: '{print $2}' | xargs
4.15.21
[root@integrate-ocp ~]# wget -q -O - https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/latest-4.19/release.txt | grep 'Name:' | awk -F: '{print $2}' | xargs
[root@integrate-ocp ~]#
```
> Use wget to fetch URL content

- zos_subsystems/db2/db2_automation_expert/daj_util.yml
- zos_subsystems/db2/db2_automation_expert/ums_login.yml
- zos_subsystems/db2/db2_automation_expert/ums_refresh.yml
Add missing UMS login, UMS refresh sample, and DAJ util playbooks
> adding ums login and refresh sample playbooks (bug #279)

- README.md
update readme with concert samples.
> update readme with concert samples.

- zos_subsystems/ims/ims_provisioning/roles/ims_catalog/tasks/main.yml
- zos_subsystems/ims/ims_provisioning/roles/ims_catalog_image_copy/tasks/main.yml
- zos_subsystems/ims/ims_provisioning/roles/ims_dataset/tasks/main.yml
- zos_subsystems/ims/ims_provisioning/roles/ims_proclib/tasks/main.yml
Upgrading z/OS core version from 1.5 to 1.11, values of the params for z/OS modules are all lowercase now.
> Support z/OSs core version: 1.11

- zos_subsystems/ims/ims_provisioning/README.md
updated the version of z/OS core and IMS Collection in the readme
> updated the version of z/OS core and IMS Collection in the readme
